name: aad_oauth
description: A Flutter OAuth package for performing user authentication against
  Azure Active Directory OAuth2 v2.0 endpoint.
version: 1.0.2
homepage: https://github.com/Earlybyte/aad_oauth

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0" # Because of PopScope at least Flutter 3.13 is required to run aad_oauth >=1.0.1

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  js: ^0.6.7
  shared_preferences: ^2.2.1
  webview_flutter: ^4.4.1
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/msalv2.js
